# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSrc',
            fields=[
                ('datasrc_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('authors', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4)),
                ('journal', models.CharField(max_length=135)),
                ('vol_city', models.CharField(max_length=16)),
                ('issue_state', models.CharField(max_length=5)),
                ('start_page', models.CharField(max_length=5)),
                ('end_page', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Datsrcln',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasrc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minicalorie.DataSrc')),
            ],
        ),
        migrations.CreateModel(
            name='DerivCd',
            fields=[
                ('deriv_cd', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('deriv_desc', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='FdGroup',
            fields=[
                ('fdgrp_cd', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('fdgrp_desc', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='FoodDes',
            fields=[
                ('ndb_no', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('long_desc', models.CharField(max_length=200)),
                ('shrt_desc', models.CharField(max_length=60)),
                ('comname', models.CharField(max_length=100)),
                ('manufacname', models.CharField(max_length=65)),
                ('survey', models.CharField(max_length=1)),
                ('ref_desc', models.CharField(max_length=135)),
                ('refuse', models.IntegerField()),
                ('sciname', models.CharField(max_length=65)),
                ('n_factor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pro_factor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fat_factor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cho_factor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fdgrp_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minicalorie.FdGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Footnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndb_no', models.CharField(max_length=5)),
                ('footnt_no', models.CharField(max_length=4)),
                ('footnt_typ', models.CharField(max_length=1)),
                ('nutr_no', models.CharField(max_length=3)),
                ('footnt_txt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Langdesc',
            fields=[
                ('factor_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Langual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minicalorie.Langdesc')),
                ('ndb_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minicalorie.FoodDes')),
            ],
        ),
        migrations.CreateModel(
            name='NutData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutr_val', models.DecimalField(decimal_places=3, max_digits=10)),
                ('num_data_pts', models.DecimalField(decimal_places=0, max_digits=5)),
                ('std_error', models.DecimalField(decimal_places=3, max_digits=8)),
                ('src_cd', models.CharField(max_length=2)),
                ('deriv_cd', models.CharField(max_length=4)),
                ('ref_ndb_no', models.CharField(max_length=5)),
                ('add_nutr_mark', models.CharField(max_length=1)),
                ('num_studies', models.IntegerField()),
                ('min', models.DecimalField(decimal_places=3, max_digits=10)),
                ('max', models.DecimalField(decimal_places=3, max_digits=10)),
                ('df', models.IntegerField()),
                ('low_eb', models.DecimalField(decimal_places=3, max_digits=10)),
                ('up_eb', models.DecimalField(decimal_places=3, max_digits=10)),
                ('stat_cmt', models.CharField(max_length=10)),
                ('addmod_date', models.CharField(max_length=10)),
                ('cc', models.CharField(max_length=1)),
                ('ndb_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minicalorie.FoodDes')),
            ],
        ),
        migrations.CreateModel(
            name='NutrDef',
            fields=[
                ('nutr_no', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('units', models.CharField(max_length=7)),
                ('tagname', models.CharField(max_length=20)),
                ('nutrdesc', models.CharField(max_length=60)),
                ('num_dec', models.CharField(max_length=1)),
                ('sr_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SrcCd',
            fields=[
                ('src_cd', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('srccd_desc', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.CharField(max_length=2)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=6)),
                ('msre_desc', models.CharField(max_length=64)),
                ('gm_wgt', models.DecimalField(decimal_places=1, max_digits=7)),
                ('num_data_pts', models.DecimalField(decimal_places=0, max_digits=4)),
                ('std_dev', models.DecimalField(decimal_places=3, max_digits=7)),
                ('ndb_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minicalorie.FoodDes')),
            ],
        ),
        migrations.AddField(
            model_name='nutdata',
            name='nutr_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minicalorie.NutrDef'),
        ),
        migrations.AddField(
            model_name='datsrcln',
            name='ndb_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minicalorie.FoodDes'),
        ),
        migrations.AddField(
            model_name='datsrcln',
            name='nutr_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minicalorie.NutrDef'),
        ),
        migrations.AlterUniqueTogether(
            name='weight',
            unique_together=set([('ndb_no', 'seq')]),
        ),
        migrations.AlterUniqueTogether(
            name='nutdata',
            unique_together=set([('ndb_no', 'nutr_no')]),
        ),
        migrations.AlterUniqueTogether(
            name='langual',
            unique_together=set([('ndb_no', 'factor_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='fooddes',
            unique_together=set([('ndb_no', 'fdgrp_cd')]),
        ),
        migrations.AlterUniqueTogether(
            name='datsrcln',
            unique_together=set([('ndb_no', 'nutr_no', 'datasrc_id')]),
        ),
    ]
