# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minicalorie', '0003_auto_20170509_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutdata',
            name='std_error',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
