# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minicalorie', '0004_auto_20170510_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='std_dev',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
    ]
