# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minicalorie', '0005_auto_20170510_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='msre_desc',
            field=models.CharField(max_length=84),
        ),
    ]
